# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Static_Pipeline_CPU/Static_Pipeline_CPU.cache/wt [current_project]
set_property parent.project_path D:/Static_Pipeline_CPU/Static_Pipeline_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/stumbEggsMachine.coe
add_files -quiet d:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/MEM.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/IF.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/EX.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/seg7x16.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/imem.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/dmem.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/pcpu.v
  D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/constrs_1/new/pcpu.xdc
set_property used_in_implementation false [get_files D:/Static_Pipeline_CPU/Static_Pipeline_CPU.srcs/constrs_1/new/pcpu.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
