# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PCPU/PCPU.cache/wt [current_project]
set_property parent.project_path D:/PCPU/PCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/EX1_23.coe
add_files -quiet d:/PCPU/PCPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/PCPU/PCPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/PCPU/PCPU.srcs/sources_1/new/mux4_5.v
  D:/PCPU/PCPU.srcs/sources_1/new/alu.v
  D:/PCPU/PCPU.srcs/sources_1/new/regfile.v
  D:/PCPU/PCPU.srcs/sources_1/new/controller.v
  D:/PCPU/PCPU.srcs/sources_1/new/stall.v
  D:/PCPU/PCPU.srcs/sources_1/new/pcreg.v
  D:/PCPU/PCPU.srcs/sources_1/new/mux4_32.v
  D:/PCPU/PCPU.srcs/sources_1/new/imem.v
  D:/PCPU/PCPU.srcs/sources_1/new/dmem.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_if.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_if_id.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_id.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_id_ex.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_ex.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_ex_mem.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_mem.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_mem_wb.v
  D:/PCPU/PCPU.srcs/sources_1/new/pipe_wb.v
  D:/PCPU/PCPU.srcs/sources_1/new/clk_divider.v
  D:/PCPU/PCPU.srcs/sources_1/new/seg7x16.v
  D:/PCPU/PCPU.srcs/sources_1/new/cpu.v
  D:/PCPU/PCPU.srcs/sources_1/new/board_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/PCPU/PCPU.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files D:/PCPU/PCPU.srcs/constrs_1/new/constraint.xdc]


synth_design -top board_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef board_top.dcp

catch { report_utilization -file board_top_utilization_synth.rpt -pb board_top_utilization_synth.pb }
