# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.cache/wt [current_project]
set_property parent.project_path D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/aaaaaa.coe
add_files -quiet d:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/add1.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/cla4.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/add4.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/add16.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/neg32.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/add32.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/luislt.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/add.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/regfiles.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/controller.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/regs_IF_ID.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/conflict_judge.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/regs_MEM_WB.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/regs_ID_EX.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/regs_EX_MEM.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/PC_reg.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/mux.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/dmem.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/alu.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/dcpu.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/imem.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/cpu_top.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/seg7x16.v
  D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/sources_1/new/dcpu_onboard.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/constrs_1/new/dcpu.xdc
set_property used_in_implementation false [get_files D:/Dynamic_Pipeline_CPU/Dynamic_Pipeline_CPU.srcs/constrs_1/new/dcpu.xdc]


synth_design -top dcpu_onboard -part xc7a100tcsg324-1


write_checkpoint -force -noxdef dcpu_onboard.dcp

catch { report_utilization -file dcpu_onboard_utilization_synth.rpt -pb dcpu_onboard_utilization_synth.pb }
